FROM golang:1.20-alpine

WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
COPY probe ./probe
RUN go mod tidy

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o probe/bin/probe probe/main.go

ENTRYPOINT [ "/app/probe/bin/probe" ]
