---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3gw-probe-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: s3gw-probe-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: s3gw-probe-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw-probe.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "s3gw-probe.selectorLabels" . | indent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
{{ include "s3gw-probe.selectorLabels" . | indent 8 }}
    spec:
      serviceAccountName: s3gw-probe-sa
      containers:
        - name: {{ .Release.Name }}
          image: {{ include "s3gw-probe.image" . | quote }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.backend.imagePullPolicy }}
          args:
            - "-s3gw-endpoint"
            - {{ .Values.s3gw.endpoint }}
            - "-wbtd"
            - '{{ .Values.s3gw.waitMSecsBeforeTriggerDeath }}'
            - "-save-data-endpoint"
            - {{ .Values.s3gw.saveDataEndpoint }}
            - "-save-data-path-style"
            - "false"
{{- range $.Values.backend.customArgs }}
            - {{ . | quote}}
{{- end }}
          env:
            - name: AWS_ACCESS_KEY
              value: {{ .Values.s3gw.accessKey }}
            - name: AWS_SECRET_KEY
              value: {{ .Values.s3gw.secretKey }}
{{- range $.Values.backend.customEnvs }}
{{- if (regexMatch "[^=]+=[^=]+" .) }}
{{- $tokens := split "=" . }}
            - name: {{ $tokens._0 }}
              value: {{ $tokens._1 | quote}}
{{- else if (regexMatch "^[^=]" .) }}
            - name: {{ . }}
{{- else }}
{{- fail (print ".Values.backend.customEnvs contains an invalid entry: " .) }}
{{- end }}
{{- end }}
          ports:
            - containerPort: 8080
              name: probe-plain
