---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw-probe.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "s3gw-probe.selectorLabels" . | indent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
{{ include "s3gw-probe.selectorLabels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
        - name: {{ .Release.Name }}
          image: {{ include "s3gw-probe.image" . | quote }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.probe.imagePullPolicy }}
          args:
            - "-v"
            - "inf"
            - "-s3gw-ns"
            - {{ default "s3gw-ha" .Values.s3gw.namespace }}
            - "-s3gw-d"
            - {{ default "s3gw-ha-s3gw" .Values.s3gw.deploymentName }}
            - "-s3gw-endpoint"
            - {{ .Values.s3gw.endpoint }}
            - "-s3gw-endpoint-ing"
            - {{ .Values.s3gw.endpointIngress }}
            - "-wbtd"
            - '{{ .Values.s3gw.waitMSecsBeforeTriggerDeath }}'
            - "-save-data-endpoint"
            - {{ .Values.saveData.endpoint }}
            - "-save-data-path-style"
            - "false"
{{- range $.Values.probe.customArgs }}
            - {{ . | quote}}
{{- end }}
          env:
            - name: AWS_ACCESS_KEY
              value: {{ .Values.s3gw.accessKey }}
            - name: AWS_SECRET_KEY
              value: {{ .Values.s3gw.secretKey }}
{{- range $.Values.probe.customEnvs }}
{{- if (regexMatch "[^=]+=[^=]+" .) }}
{{- $tokens := split "=" . }}
            - name: {{ $tokens._0 }}
              value: {{ $tokens._1 | quote}}
{{- else if (regexMatch "^[^=]" .) }}
            - name: {{ . }}
{{- else }}
{{- fail (print ".Values.probe.customEnvs contains an invalid entry: " .) }}
{{- end }}
{{- end }}
          ports:
            - containerPort: 8080
              name: probe-plain
