{{- if .Values.probe.ingress.enabled }}
---
# Backend Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Release.Name }}-no-tls'
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw-probe.labels" . | indent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares:
      '{{ .Release.Namespace }}-{{ include "s3gw-probe.CORSMiddlewareName" . }}@kubernetescrd'
spec:
  rules:
    - host: '{{ include "s3gw-probe.serviceName" . }}.{{ .Values.probe.publicDomain }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: '{{ include "s3gw-probe.serviceName" . }}'
                port:
                  number: 80
---
# Middleware for Traefik
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "s3gw-probe.CORSMiddlewareName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw-probe.labels" . | indent 4 }}
spec:
  headers:
    accessControlAllowMethods:
      - "DELETE"
      - "GET"
      - "HEAD"
      - "POST"
      - "PUT"
      - "OPTIONS"
    accessControlAllowOriginList:
      - "*"
    accessControlAllowHeaders:
      - "*"
    accessControlExposeHeaders:
      - "*"
{{- end }}
