---
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "s3gw-probe.serviceName" . }}'
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw-probe.labels" . | indent 4 }}
spec:
  selector:
{{ include "s3gw-probe.selectorLabels" . | indent 4 }}
  ports:
    - name: probe-plain
      protocol: TCP
      port: 80
      targetPort: probe-plain
